Join session component
srujanr40/dogfish pull request #13
Opened 2023-06-10 19:22 UTC by edvinkeskin

implemented parts of join component then merged profile component

2023-06-10 19:36 UTC, edvinkeskin commented
https://github.com/srujanr40/dogfish/assets/71086447/0481c0f9-56d3-4d7c-85b7-5d1052777c6b

I intended for the blue boxes to be replaced with the chatbox and maps API. All info which is inputted in the create session page is visible on the left side. We can make UI changes, open to reviews

2023-06-13 01:51 UTC, srujanr40 requested changes

2023-06-13 01:51 UTC, srujanr40 commented on src/client/reducers/fetchedSessionReducer.js
Think we could combine this with the `sessionReducer` and add an action within there for 'FETCH_SESSIONS'? You can update the empty initial state on that reducers with this dummy data too, just to reduce some duplication

2023-06-13 01:51 UTC, srujanr40 commented on src/client/components/JoinSession/JoinSession.jsx
> +                        <img className="placeholder-image" src={stockPlaceholderImageURL} alt="placeholder"/>
Taqdeer has a component set up for the placeholder image. Wanna use that instead of typing this up again?

2023-06-13 01:51 UTC, srujanr40 commented on src/client/reducers/fetchedSessionReducer.js
> +        playersNeeded: 3, groupId: 7},]
This data would also need to include the image URL

2023-06-14 08:41 UTC, edvinkeskin commented on src/client/reducers/fetchedSessionReducer.js
> +        playersNeeded: 3, groupId: 7},]
added image variable which has imageURL for initialState array elements

2023-06-14 08:45 UTC, edvinkeskin commented on src/client/components/JoinSession/JoinSession.jsx
> +                        <img className="placeholder-image" src={stockPlaceholderImageURL} alt="placeholder"/>
if you're referring to the uploadImage component I had tried using it but it has a file upload component which doesn't serve a purpose for JoinSession component

2023-06-14 09:04 UTC, edvinkeskin commented on src/client/reducers/fetchedSessionReducer.js
I was able to merge our reducers but one thing I noticed on my branch handleSubmit (which dispatchs changes to the reducer) isn't called, is this normal or is my branch behind. Should I just start calling handleSubmit when submit button is clicked?

2023-06-14 16:49 UTC, srujanr40 commented on src/client/components/JoinSession/JoinSession.jsx
> +                        <img className="placeholder-image" src={stockPlaceholderImageURL} alt="placeholder"/>
Ah it includes an upload. Yeah my bad, disregard this.

2023-06-14 19:17 UTC, srujanr40 approved these changes

2023-06-14 19:19 UTC, merged